### ISSUE TITLE
RocketCDN CNAME change

### ISSUE THREAD

**Issue by piotrbak** [wp-media/rocketcdn-plugin#40]
**Is your feature request related to a problem? Please describe.**
In the upcoming version we'll need to change the RocketCDN CNAMEs automatically

**Describe the solution you'd like**
The Acceptance Criteria is described here:
https://www.notion.so/wpmedia/RocketCDN-CNAME-change-d72cd2baa88b49b7b4cb65b348440564?pvs=4

**Comment by Khadreal** [comment]
### Scope a solution ✅
In this [file](https://github.com/wp-media/rocketcdn-plugin/blob/ca4f5fb003a016f60841decdf06760b59f0dedb1/src/Admin/Notices/Subscriber.php#L8) add a new method for the display notice
```
public function display_update_notice() {
		$this->notices->display_update_notice();
	}
```

Add the method name to the the admin_notices array  https://github.com/wp-media/rocketcdn-plugin/blob/ca4f5fb003a016f60841decdf06760b59f0dedb1/src/Admin/Notices/Subscriber.php#L32

In this [file](https://github.com/wp-media/rocketcdn-plugin/blob/ca4f5fb003a016f60841decdf06760b59f0dedb1/src/Admin/Notices/Notices.php#L11) we create a new method for the display_update_notice used in the subscriber class above 

```
public function display_update_notice() {
    if ( ! current_user_can( 'rocket_manage_options' ) ) {
        return;
    }

    if ( $this->options->get( 'api_key' ) ) {
        return;
    }

    //we should have  a check to know the customer previous version, we currently don't store it we might need to 

    $message = sprintf(
			__( '%1$sRocketCDN:%2$s We\'ve updated your RocketCDN CNAME from %3$s to %4$s. The change is already applied to the plugin settings. If you were using the CNAME in your code, make sure to update it to: %4$s If you have any questions %5$sContact support%6$s.', 'rocketcdn' ),
			'<strong>',
			'</strong>',
            'previous_cdn_url',
            'cdn_url',
			'<a href="link_to_support">',
			'</a>'
		);

		echo '<div class="notice notice-info"><p>' . $message . '</p></div>'; 
}
```

Add a new file(upgrade.php) to include directory, this would have an function that will be added as a callback to the `admin_init` filter and the file should be required in this [file](https://github.com/wp-media/rocketcdn-plugin/blob/ca4f5fb003a016f60841decdf06760b59f0dedb1/rocketcdn.php#L22)
The upgrade function that  will be created in upgrade.php should set in motion series of event
1 - Save current cdn as an option to a new key `previous_cdn_url`
2 - Call either of `add_option_rocketcdn_api_key` or `update_option_rocketcdn_api_key` filter to update cdn_url
3 - Delete the current `rocketcdn_customer_data` transient and set a new one.

Add new test to cover, and update existing ones

### Estimate the effort ✅ 
Effort [M]

**Comment by Tabrisrp** [comment]
That's a good base, but it requires more refinement for some parts.

- On the upgrade part, it should be in a class like the rest of the code
- To be able to display the notice only for versions under the one including this change, we need to start storing the version
- The update of the CDN URL doesn't need to call filters, we can call `update_option()` directly (or use the Option class from launchpad)

**Comment by Khadreal** [comment]
> To be able to display the notice only for versions under the one including this change, we need to start storing the version

How best do you think we can handle this part or should we do a minor to handle this ? I think handling at one go might be a challenge.

Updated the grooming based on the feedbacks

**Comment by Tabrisrp** [comment]
We can add the version number on this hook https://developer.wordpress.org/reference/hooks/upgrader_process_complete/, and have a condition if the version number is already set, we bail.

I also see that the notice needs to be dismissible, so we need to implement a system that can make the dismiss permanent, like we have in WPR and Imagify.

**Comment by MathieuLamiot** [comment]
As the approach is based on the RocketCDN API, the plugin release with this change must happen after this is released: https://github.com/wp-media/rocket-cdn/issues/546

**Comment by MathieuLamiot** [comment]
Moving back to Grooming to Review following Khadreal's edit of the grooming.

**Comment by remyperona** [comment]
LGTM

**Comment by MathieuLamiot** [comment]
The backend update is ready [here](https://github.com/wp-media/rocket-cdn/issues/546), so we can consider testing completely on staging for instance.
